//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHomeWebAplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDSHEntities : DbContext
    {
        public BDSHEntities()
            : base("name=BDSHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cleanliness> Cleanliness { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<District> District { get; set; }
        public virtual DbSet<GetUp> GetUp { get; set; }
        public virtual DbSet<GoToBed> GoToBed { get; set; }
        public virtual DbSet<House> House { get; set; }
        public virtual DbSet<Landlord> Landlord { get; set; }
        public virtual DbSet<LifeStyle> LifeStyle { get; set; }
        public virtual DbSet<Pet> Pet { get; set; }
        public virtual DbSet<Priority> Priority { get; set; }
        public virtual DbSet<Property> Property { get; set; }
        public virtual DbSet<Province> Province { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
