//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHomeWebAplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.Property = new HashSet<Property>();
        }
    
        public long IdDepartmet { get; set; }
        public int Rooms { get; set; }
        public int Bathrooms { get; set; }
        public bool Luminosity { get; set; }
        public string Description { get; set; }
        public long idService { get; set; }
        public int IdDistrict { get; set; }
        public int IdProvince { get; set; }
        public int IdRegion { get; set; }
        public decimal Price { get; set; }
    
        public virtual District District { get; set; }
        public virtual Province Province { get; set; }
        public virtual Region Region { get; set; }
        public virtual Region Region1 { get; set; }
        public virtual Service Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Property> Property { get; set; }
    }
}
