//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHomeWebAplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Landlord
    {
        public int GraduationYear { get; set; }
        public string LastName { get; set; }
        public string DNI { get; set; }
        public int IdRegion { get; set; }
        public int IdProvince { get; set; }
        public int IdDistrict { get; set; }
        public string Addres { get; set; }
        public string Phone { get; set; }
        public System.DateTime Birthdate { get; set; }
        public long IdProperty { get; set; }
        public long IdLandlord { get; set; }
    
        public virtual District District { get; set; }
        public virtual Region Region { get; set; }
        public virtual Property Property { get; set; }
        public virtual Property Property1 { get; set; }
        public virtual Province Province { get; set; }
    }
}
