//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHomeWebAplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.Property = new HashSet<Property>();
        }
    
        public long IDRoom { get; set; }
        public bool Luminosity { get; set; }
        public string Description { get; set; }
        public int IdProvince { get; set; }
        public int IdDistrict { get; set; }
        public int IdRegion { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual District District { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Property> Property { get; set; }
        public virtual Property Property1 { get; set; }
        public virtual Province Province { get; set; }
        public virtual Region Region { get; set; }
    }
}
